### ISSUE TITLE
plugin里添加umi-plugin-antd-theme后报错

### ISSUE THREAD

**Issue by tigerHeeJS** [chenshuai2144/umi-plugin-antd-theme#21]
```js
[
  "umi-plugin-antd-theme",
  {
    theme: [
      {
        key: "light",
        fileName: "light.css",
        theme: "light",
        modifyVars: {
          "@primary-color": "#0FCD8C",
          "@btn-primary-color": "#01081E",
          "@tooltip-color": "rgba(0,0,0,0.65)",
          "@tooltip-bg": "#FFF",
          "@kc-limit-width": "1200px",
          "@kc-mb-width": "600px"
        }
      },
      {
        key: "dark",
        fileName: "dark.css",
        theme: "dark",
        modifyVars: {
          "@primary-color": "#0FCD8C",
          "@btn-primary-color": "#01081E",
          "@tooltip-color": "rgba(0,0,0,0.65)",
          "@tooltip-bg": "#FFF",
          "@kc-limit-width": "1200px",
          "@kc-mb-width": "600px"
        }
      }
    ]
  }
];
```

Cannot find module 'antd/dist/dark-theme'
    at Service.resolvePlugins (/Users/tigerhee/Desktop/kupo/explorer/node_modules/umi-build-dev/lib/Service.js:176:15)
    at new Service (/Users/tigerhee/Desktop/kupo/explorer/node_modules/umi-build-dev/lib/Service.js:150:25)
    at Object.<anonymous> (/Users/tigerhee/Desktop/kupo/explorer/node_modules/umi/lib/scripts/realDev.js:49:25)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Jesyjun** [comment]
您好 请问有没有解决了

**Comment by buyaotutou** [comment]
最后是怎么解决了呢，我也碰到同样的问题
