### ISSUE TITLE
antpro@2.2.0，根据官方文档添加，报错了

### ISSUE THREAD

**Issue by Jesyjun** [chenshuai2144/umi-plugin-antd-theme#22]
> ant-design-pro@2.2.0 start /Users/doudou/ccp_front/holmes/ccp_frontend_demo
> cross-env APP_TYPE=site umi dev

🚀 Starting Umi UI using umi@2.13.13...
⛽️ Ready on http://localhost:3000/
/Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_umi-build-dev@1.18.5@umi-build-dev/lib/Service.js:182
        throw new Error(e);
        ^

Error: Error: Plugin /Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/umi-plugin-antd-theme/lib/index.js execute failed

Cannot find module 'antd/dist/dark-theme'
Require stack:
- /Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_@ant-design_dark-theme@2.0.2@@ant-design/dark-theme/index.js
- /Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_antd-pro-merge-less@3.0.10@antd-pro-merge-less/index.js
- /Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_umi-plugin-antd-theme@2.1.2@umi-plugin-antd-theme/lib/index.js
- /Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_umi-build-dev@1.18.5@umi-build-dev/lib/getPlugins.js
- /Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_umi-build-dev@1.18.5@umi-build-dev/lib/Service.js
- /Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_umi@2.13.13@umi/lib/scripts/realDev.js
    at Service.resolvePlugins (/Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_umi-build-dev@1.18.5@umi-build-dev/lib/Service.js:182:15)
    at new Service (/Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_umi-build-dev@1.18.5@umi-build-dev/lib/Service.js:156:25)
    at Object.<anonymous> (/Users/doudou/ccp_front/holmes/ccp_frontend_demo/node_modules/_umi@2.13.13@umi/lib/scripts/realDev.js:49:25)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.2.0 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/doudou/.tnpm/_logs/2020-06-09T08_13_23_372Z-debug.log
[tnpm] subprocess:/usr/local/lib/node_modules/tnpm/lib/npm_child_process.js exit code: 1, signal: null

参考的文档地址https://pro.ant.design/docs/dynamic-theme-cn
里面的v2版本方式

**Comment by buyaotutou** [comment]
我也是碰到了同样的问题
